SELECT PC.model, PC.speed as MHz, PC.hd as Gb
FROM PC
WHERE PC.price < 1200;

SELECT DISTINCT PRODUCT.maker
FROM PRODUCT
WHERE PRODUCT.TYPE = 'Printer';

SELECT l.model, l.ram, l.screen
FROM LAPTOP l
WHERE l.price > 1000;

SELECT *
FROM PRINTER
WHERE PRINTER.color = 'y';

SELECT p.model, p.speed, p.hd 
FROM PC p
WHERE (p.cd = '12x' OR p.cd = '16x') AND p.price < 2000;

SELECT PRODUCT.maker, LAPTOP.speed
FROM PRODUCT, LAPTOP
WHERE LAPTOP.hd > 9 AND PRODUCT.model = LAPTOP.model;

(SELECT PRODUCT.model,LAPTOP.price
FROM PRODUCT, LAPTOP
WHERE PRODUCT.maker='B' AND PRODUCT.model=LAPTOP.model)
UNION
(SELECT PRODUCT.model,PRINTER.price
FROM PRODUCT, PRINTER
WHERE PRODUCT.maker='B' AND PRODUCT.model=PRINTER.model)
UNION
(SELECT PRODUCT.model,PC.price
FROM PRODUCT, PC
WHERE PRODUCT.maker='B' AND PRODUCT.model=PC.model);

(SELECT PRODUCT.maker
FROM PRODUCT, LAPTOP
WHERE PRODUCT.model = LAPTOP.MODEL)
EXCEPT
(SELECT PRODUCT.maker
FROM PRODUCT, PC
WHERE PRODUCT.model = PC.MODEL);

SELECT PC.hd
FROM PC
GROUP BY pc.hd
HAVING COUNT(PC.hd) > 1;

SELECT pc1.model, pc2.model
FROM PC AS pc1, PC AS pc2
WHERE pc1.ram = pc2.ram AND pc1.speed=pc2.speed AND pc1.model!=pc2.model AND pc1.code<pc2.code;


SELECT DISTINCT PRODUCT.maker 
FROM PRODUCT
WHERE PRODUCT.model IN 
(SELECT PC.model
FROM PC
WHERE PC.speed > 400 
GROUP BY PC.model
HAVING COUNT(PC.model) > 1);

SELECT DISTINCT PRODUCT.MAKER 
FROM PRODUCT, PC 
WHERE PRODUCT.model=PC.model AND PC.speed > 500;

SELECT PRINTER.code, PRINTER.model, PRINTER.price 
FROM PRINTER
WHERE PRINTER.PRICE >= ALL(SELECT PRINTER.price 
					      FROM PRINTER);

SELECT *
FROM LAPTOP
WHERE LAPTOP.speed < ALL(SELECT PC.speed
						 FROM PC);

SELECT PRODUCT.model, pr.price 
FROM PRODUCT, (SELECT PC.model, PC.PRICE 
			   FROM PC
			   UNION
			   SELECT LAPTOP.MODEL, LAPTOP.price
			   FROM LAPTOP
			   UNION SELECT PRINTER.MODEL, PRINTER.price
			   FROM PRINTER) pr
WHERE PRODUCT.model=PR.model AND pr.price >= ALL(SELECT PC.price
											     FROM PC
												 UNION
												 SELECT LAPTOP.price
												 FROM LAPTOP
												 UNION
												 SELECT PRINTER.price
												 FROM PRINTER);

SELECT PRODUCT.maker
FROM PRINTER, PRODUCT
WHERE PRODUCT.MODEL=PRINTER.model AND PRINTER.color='y' AND 
PRINTER.price <= ALL(SELECT PRINTER.price
					 FROM PRINTER
				     WHERE PRINTER.color='y');

SELECT PRODUCT.maker
FROM PC p, PRODUCT
WHERE PRODUCT.model=p.model AND
p.ram<= ALL(SELECT PC.ram
			 FROM PC) AND
p.speed >= ALL(SELECT PC.speed
			 FROM PC
			 WHERE PC.ram = p.RAM);


SELECT PRODUCT.maker, PRODUCT.model, PRODUCT.type
FROM PRODUCT
WHERE PRODUCT.MODEL NOT IN(
(SELECT LAPTOP.MODEL
FROM LAPTOP)
 UNION
(SELECT PC.MODEL
 FROM PC)
 UNION
 (SELECT PRINTER.MODEL
 FROM PRINTER));

SELECT DISTINCT PRODUCT.maker
FROM PRODUCT
WHERE PRODUCT.MAKER IN(
(SELECT PRODUCT.MAKER
FROM LAPTOP
JOIN PRODUCT
ON PRODUCT.model=LAPTOP.model)
INTERSECT
(SELECT PRODUCT.MAKER
FROM PRODUCT
JOIN PRINTER
ON PRODUCT.model=PRINTER.model)
);  

SELECT DISTINCT l1.HD
FROM LAPTOP l1
JOIN LAPTOP l2
ON L1.MODEL!=L2.model
AND l1.hd=l2.hd;

SELECT PC.MODEL 
FROM PC
JOIN PRODUCT
ON PRODUCT.MAKER IS NULL
AND PRODUCT.MODEL = PC.MODEL;


SELECT AVG(PC.speed)
FROM PC;

SELECT product.maker, AVG(LAPTOP.screen)
FROM LAPTOP
JOIN PRODUCT
ON PRODUCT.model=laptop.model
GROUP BY product.maker; 

SELECT AVG(LAPTOP.SPEED)
FROM LAPTOP
WHERE LAPTOP.price>1000;

SELECT PRODUCT.MAKER, AVG(PC.price)
FROM PC
JOIN PRODUCT
ON PC.MODEL=PRODUCT.MODEL
WHERE PRODUCT.MAKER='A'
GROUP BY product.MAKER;

SELECT PRODUCT.maker, AVG(PRICES.PRICES)
FROM PRODUCT, (SELECT PC.PRICE AS PRICES 
FROM PC
JOIN PRODUCT
ON PRODUCT.MODEL=PC.MODEL
AND PRODUCT.MAKER='B'
UNION ALL
(SELECT LAPTOP.PRICE AS PRICES
FROM LAPTOP
JOIN PRODUCT
ON PRODUCT.MODEL=LAPTOP.MODEL
AND PRODUCT.MAKER='B')) AS PRICES 
WHERE PRODUCT.maker='B'
GROUP BY PRODUCT.maker;

SELECT PC.speed, AVG(PC.price)
FROM PC
GROUP BY PC.speed;

SELECT PRODUCT.maker, COUNT(PC.code)
FROM PRODUCT
JOIN PC
ON PRODUCT.MODEL=PC.MODEL
GROUP BY product.maker 
HAVING COUNT(PC.CODE) >= 3;

SELECT PRODUCT.MAKER, PC.PRICE
FROM PRODUCT
JOIN PC
ON PRODUCT.model=PC.MODEL
AND PC.price = (SELECT MAX(PC.price)
			     FROM PC);

SELECT PC.SPEED, AVG(PC.price)
FROM PC
WHERE PC.SPEED > 800
GROUP BY PC.SPEED;

SELECT PRODUCT.MAKER, AVG(PC.hd) 
FROM PC
JOIN PRODUCT
ON PRODUCT.model=PC.MODEL
AND PRODUCT.MAKER IN (SELECT PRODUCT.MAKER
					  FROM PRODUCT
                      JOIN PRINTER
					  ON PRODUCT.MODEL=PRINTER.MODEL)
GROUP BY product.MAKER;

SELECT LAPTOP.MODEL, LAPTOP.code, LAPTOP.SCREEN 
FROM LAPTOP
WHERE LAPTOP.SCREEN='15'
OR LAPTOP.SCREEN='11';

SELECT DISTINCT p.model
FROM PC p
JOIN PRODUCT l
ON l.model=p.model
AND p.price < (SELECT MIN(LAPTOP.price)
                  FROM LAPTOP
				  JOIN PRODUCT
				  ON PRODUCT.MODEL=LAPTOP.model
				  AND PRODUCT.maker=l.maker);  


SELECT PC.model, AVG(PC.price)
FROM PC
JOIN PRODUCT K
ON PC.MODEL=K.model
GROUP BY PC.MODEL, K.maker
HAVING AVG(PC.price) < (SELECT MIN(LAPTOP.price)
						FROM LAPTOP
						JOIN PRODUCT
						ON LAPTOP.model=PRODUCT.MODEL
						AND PRODUCT.MAKER=K.MAKER);

SELECT C1.CODE, PRODUCT.MAKER, COUNT(C2.code) 
FROM PC C1, PC C2, PRODUCT
WHERE PRODUCT.MODEL = C1.MODEL
AND PRODUCT.MODEL = C2.MODEL
AND C1.price <= C2.price
GROUP BY C1.CODE, PRODUCT.maker;
