
USE Movies;

INSERT INTO MOVIESTAR(NAME, BIRTHDATE)
VALUES('Nicole Kidman', '1967-06-20');

DELETE FROM MOVIEEXEC
WHERE MOVIEEXEC.NETWORTH < 30000000;

DELETE FROM MOVIESTAR
WHERE MOVIESTAR.ADDRESS IS NULL;

USE PC;

INSERT INTO PC(CODE, MODEL, SPEED, RAM, HD, CD, PRICE)
VALUES (12,'1100',2400,2048,500,'52x' ,299)
INSERT INTO PRODUCT(MODEL, MAKER, TYPE)
VALUES ('1100','C','PC');

DELETE FROM PC
WHERE PC.MODEL='1100';

DELETE FROM LAPTOP
WHERE LAPTOP.MODEL IN (SELECT product.model 
                    FROM PRODUCT
					WHERE product.maker NOT IN (SELECT product.maker
					                            FROM PRODUCT
												WHERE product.TYPE='Printer'));

UPDATE PRODUCT
SET PRODUCT.maker = 'A'
WHERE product.maker = 'B';

UPDATE PC
SET PC.price = PC.price/2, PC.hd=PC.hd+20;

UPDATE LAPTOP
SET LAPTOP.screen = LAPTOP.screen+1
WHERE LAPTOP.MODEL IN (SELECT PRODUCT.model
                      FROM PRODUCT
					  WHERE PRODUCT.maker='B'
					  AND product.type='Laptop');


USE Ships;

INSERT CLASSES(CLASSES.CLASS, CLASSES.TYPE, CLASSES.COUNTRY, CLASSES.BORE, CLASSES.DISPLACEMENT)
VALUES('Nelson','bb','Gt. Britain',16,34000);

INSERT SHIPS(SHIPS.NAME, SHIPS.CLASS, SHIPS.LAUNCHED)
VALUES('Nelson','Nelson',1927);

INSERT SHIPS(SHIPS.NAME, SHIPS.CLASS, SHIPS.LAUNCHED)
VALUES('Rodney','Nelson',1927);

DELETE FROM SHIPS
WHERE SHIPS.NAME IN (SELECT DISTINCT OUTCOMES.SHIP
					 FROM OUTCOMES
					 WHERE OUTCOMES.RESULT='sunk');

UPDATE CLASSES
SET BORE = BORE * 2.5, DISPLACEMENT = DISPLACEMENT / 1.1;
